In [3]:
# # from mysql import connector
# import sys
# !{sys.executable} -m pip install pandas




import mysql.connector
from dotenv import load_dotenv
import os 
import pandas as pd

In [4]:
load_dotenv()

user = os.getenv('USER')
password = os.getenv('PASSWORD')
host = os.getenv('HOST')

database = 'swiftmarket'

In [5]:
connection = mysql.connector.connect(
                 user = user,
                 password = password,
                 host = host,
                 database = database
)

cursor = connection.cursor()

In [6]:
connection.is_connected()

True

In [7]:
query = '''show tables'''
cursor.execute(query)
rows = cursor.fetchall()
for row in rows :
    print(row)

('categories',)
('customers',)
('employees',)
('salesdata',)
('subcategories',)
('suppliers',)

In [8]:
query = '''select * from salesdata limit 5'''
cursor.execute(query)
rows = cursor.fetchall()
for row in rows :
    print(row)

(23000, 'C-2023-100-12', 6002, 1100, datetime.date(2023, 5, 2), 2, Decimal('176432.00'))
(23001, 'C-2023-100-141', 6029, 1115, datetime.date(2023, 12, 26), 2, Decimal('47172.00'))
(23002, 'C-2023-100-86', 6029, 1035, datetime.date(2023, 3, 26), 2, Decimal('47172.00'))
(23003, 'C-2023-100-72', 6006, 1016, datetime.date(2023, 8, 1), 2, Decimal('117644.00'))
(23004, 'C-2023-100-142', 6030, 1067, datetime.date(2023, 3, 6), 5, Decimal('336560.00'))

In [9]:
cursor.column_names

('SaleID',
 'CustomerID',
 'SubcatID',
 'EmployeeID',
 'SaleDate',
 'Quantity',
 'TotalPrice')

In [10]:
pd.DataFrame(data=rows , columns=cursor.column_names)

,SaleID,CustomerID,SubcatID,EmployeeID,SaleDate,Quantity,TotalPrice
0,23000,C-2023-100-12,6002,1100,2023-05-02,2,176432.00
1,23001,C-2023-100-141,6029,1115,2023-12-26,2,47172.00
2,23002,C-2023-100-86,6029,1035,2023-03-26,2,47172.00
3,23003,C-2023-100-72,6006,1016,2023-08-01,2,117644.00
4,23004,C-2023-100-142,6030,1067,2023-03-06,5,336560.00

In [13]:
# Func. 
def read_query(query):
    cursor.execute(query)
    rows = cursor.fetchall()
    return pd.DataFrame(data = rows, columns=cursor.column_names)

In [14]:
query = '''select * from customers limit 5'''
read_query(query)

,CustomerID,FirstName,LastName,Email,Phone,Address,State
0,C-2023-100-1,Mahika,Sunder,MahikaSunder_11@zmail.com,03412176590,"H.No. 155, Chana",Assam
1,C-2023-100-10,Zeeshan,Vasa,ZeeshanVasa_1@zmail.com,+911151051656,"52, Roy Nagar",Tripura
2,C-2023-100-100,Aaina,Sachdeva,AainaSachdeva_9@zmail.com,+918834507719,"75/92, Kade Marg",Nagaland
3,C-2023-100-101,Shray,Bajwa,ShrayBajwa_11@zmail.com,07410498662,"45, Bora Ganj",Manipur
4,C-2023-100-102,Navya,Dash,NavyaDash_5@zmail.com,+917644200850,70/782\nBahl Road,Kerala

In [15]:
query = '''select * from salesdata limit 5'''
read_query(query)

,SaleID,CustomerID,SubcatID,EmployeeID,SaleDate,Quantity,TotalPrice
0,23000,C-2023-100-12,6002,1100,2023-05-02,2,176432.00
1,23001,C-2023-100-141,6029,1115,2023-12-26,2,47172.00
2,23002,C-2023-100-86,6029,1035,2023-03-26,2,47172.00
3,23003,C-2023-100-72,6006,1016,2023-08-01,2,117644.00
4,23004,C-2023-100-142,6030,1067,2023-03-06,5,336560.00

In [26]:
query = '''
        select c.firstname, c.lastname, sum(s.totalprice) AS TOTALPRICE
        from customers as c 
        inner join salesdata as s on 
        c.customerid = s.customerid
        group by c.firstname, c.lastname
        ORDER BY TOTALPRICE DESC
        LIMIT 10

'''

In [27]:
read_query(query)

  firstname     lastname   TOTALPRICE
0   Vaibhav         Gill  16917070.00
1   Manikya       Doctor  16270438.00
2      Veer        Loyal  13016064.00
3  Priyansh        Yadav  12629337.00
4      Riya        Saraf  12599608.00
5     Vanya  Ranganathan  12455437.00
6     Dhruv         Apte  12280916.00
7    Tarini        Khare  12130487.00
8   Yuvraj          Lata  11868602.00
9      Rhea      Chander  11704275.00